auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Joebon's world
url: http://korbinzhao.github.io
feed: /atom.xml
author_info: <a href="http://korbinzhao.github.io">Joebon</a>


